spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: myadmin
    password: dlwjdals1*
    url: jdbc:mariadb://localhost:3307/dobaerangshop

  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

